Repository puppetlabs/pdk, pull requests merged in 2019-08, with the labels that each got.

#724 (GH-722) Do not emit nil targets for validators against a directory
  lib/pdk/validate/base_validator.rb
  spec/unit/pdk/validate/base_validator_spec.rb
Labels: bug

#725 Handle deleted template files for new module
  lib/pdk/generate/module.rb
  spec/unit/pdk/generate/module_spec.rb
Labels: bug

#730 (PDK-871) Relax dependencies on tty-* gems
  lib/pdk/cli/exec.rb
  lib/pdk/cli/exec/command.rb
  lib/pdk/cli/exec_group.rb
  lib/pdk/cli/util/interview.rb
  lib/pdk/cli/util/spinner.rb
  lib/pdk/util/ruby_version.rb
  pdk.gemspec
  spec/spec_helper.rb
Labels: dependency, enhancement

#729 (PDK-1363) Apply init templates during module convert
  lib/pdk/module/convert.rb
  lib/pdk/module/metadata.rb
  lib/pdk/module/templatedir.rb
  lib/pdk/util/filesystem.rb
  spec/acceptance/convert_spec.rb
  spec/acceptance/update_spec.rb
  spec/unit/pdk/module/convert_spec.rb
  spec/unit/pdk/module/metadata_spec.rb
  spec/unit/pdk/module/update_spec.rb
Labels: enhancement
