Repository puppetlabs/pdk, pull requests merged in 2020-02, with the labels that each got.

#843 (PDK-1600) Release 1.16.0
  CHANGELOG.md
  lib/pdk/version.rb
  locales/pdk.pot
Labels: maintenance

#844 (PDK-1605) Bump version to 1.17.0.pre
  lib/pdk/version.rb
Labels: maintenance

#846 (maint) Add basic tests for running PDK unprivileged
  package-testing/spec/package/support/serverspec_monkeypatch.rb
  package-testing/spec/package/unprivileged_user_spec.rb
Labels: WIP, blocked

#852 (PDK-1522) Update package tests for OSX 10.15
  package-testing/Gemfile
  package-testing/spec/package/support/spec_utils.rb
Labels: packaging

#842 (PDK-1113) Use PDK configuration instead of AnswerFile class
  lib/pdk.rb
  lib/pdk/answer_file.rb
  lib/pdk/cli.rb
  lib/pdk/cli/convert.rb
  lib/pdk/config.rb
  lib/pdk/config/namespace.rb
  lib/pdk/generate/module.rb
  lib/pdk/util/template_uri.rb
  spec/acceptance/convert_spec.rb
  spec/acceptance/support/in_a_new_module.rb
  spec/acceptance/template_ref_spec.rb
  spec/support/mock_configuration.rb
  spec/unit/pdk/answer_file_spec.rb
  spec/unit/pdk/cli/convert_spec.rb
  spec/unit/pdk/config_spec.rb
  spec/unit/pdk/generate/module_spec.rb
  spec/unit/pdk/generate/puppet_object_spec.rb
  spec/unit/pdk/util/template_uri_spec.rb
Labels: WIP

#861 (PDK-1624) Prepare 1.17.0 release
  CHANGELOG.md
  lib/pdk/version.rb
  locales/pdk.pot
Labels: maintenance

#863 (PDK-1629) Bump to 1.18.0.pre
  lib/pdk/version.rb
Labels: maintenance
