Repository puppetlabs/pdk, pull requests merged in 2021-07, with the labels that each got.

#1121 (GH-1113) (GH-917) Fix forge-token handling
  lib/pdk/cli/release.rb
  spec/unit/pdk/cli/release_spec.rb
Labels: bug

#1125 (maint) Update beaker-hostgenerator to support newer platforms
  package-testing/Gemfile
Labels: dependency

#1114 (GH-1118) Add ability to skip validating files
  docs/pdk_testing.md
  lib/pdk/config.rb
  lib/pdk/validate/invokable_validator.rb
  spec/unit/pdk/config_spec.rb
  spec/unit/pdk/validate/invokable_validator_spec.rb
Labels: enhancement

#1124 (GH-1115) Bump `json_pure` to `~> 2.5.1` on Ruby `>= 2.7`
  pdk.gemspec
Labels: blocked, dependency

#1130 (GH-1128) Fix package-testing issues in PDK
  package-testing/Gemfile
  package-testing/Rakefile
  package-testing/spec/package/support/install_pdk.rb
  package-testing/spec/package/support/spec_utils.rb
  package-testing/spec/package/version_selection_spec.rb
Labels: maintenance
