Repository puppetlabs/pdk, pull requests merged in 2021-04, with the labels that each got.

#1046 (MAINT) Mock PDK::Util::Env.fetch resp for util_spec.rb:292
  spec/unit/pdk/util_spec.rb
Labels: maintenance

#1044 (MAINT) Release prep for PDK 2.1.0.0
  CHANGELOG.md
  docs/pdk.md
  docs/release_notes_pdk.md
  lib/pdk/version.rb
  spec/spec_helper.rb
Labels: maintenance

#1048 (main) Bump to 2.2.0.pre
  lib/pdk/version.rb
Labels: maintenance

#1040 (GH-1039) Acceptance tests for Linux on GHActions Workflow
  .dependency_decisions.yml
  .fixtures.yml
  .github/workflows/acceptance.yml
  .github/workflows/spec.yml
  .gitignore
  .travis.yml
  Gemfile
  Rakefile
  spec/acceptance/bundle_spec.rb
Labels: ci, maintenance

#1047 (MAINT) Exclude lib/pdk/version.rb from SimpleCov
  spec/spec_helper.rb
Labels: maintenance

#1072 (MAINT) Update Litmus inventory.yaml location in acceptance.yml
  .github/workflows/acceptance.yml
Labels: maintenance

#1071 (puppetlabs/devx#15) `pdk validate` overview ref doc
  reference/validate/REFERENCE.md
Labels: documentation
