Repository puppetlabs/pdk, pull requests merged in 2023-05, with the labels that each got.

#1242 updates the contact information section on README
  README.md
Labels: maintenance, MayTheSourceBeWithYou

#1248 (CONT-935) Fix issues with PDK package and tests
  .github/workflows/ci.yml
  Rakefile
  docs/pdk_converting_modules.md
  docs/pdk_creating_modules.md
  lib/pdk/analytics/util.rb
  lib/pdk/cli/exec/interactive_command.rb
  lib/pdk/config/namespace.rb
  lib/pdk/module/metadata.rb
  spec/acceptance/convert_spec.rb
  spec/acceptance/support/in_a_new_module.rb
  spec/acceptance/test_unit_spec.rb
  spec/acceptance/update_spec.rb
  spec/acceptance/version_changer_spec.rb
  spec/unit/pdk/cli/validate_spec.rb
  spec/unit/pdk/util/puppet_version_spec.rb
Labels: bug

#1247 (MAINT) Fix package tests
  .rubocop.yml
  package-testing/Gemfile
  package-testing/config/options.rb
  package-testing/spec/package/update_module_spec.rb
  package-testing/spec/package/version_selection_spec.rb
  package-testing/spec/spec_helper_package.rb
Labels: maintenance

#1249 (CONT-1024) Remove config command
  lib/pdk/cli.rb
  lib/pdk/cli/config.rb
  lib/pdk/cli/config/get.rb
  spec/acceptance/config_get_spec.rb
  spec/acceptance/config_spec.rb
Labels: backwards-incompatible

#1246 (ISS-1123) Verbose output w/ junit file
  lib/pdk/tests/unit.rb
Labels: enhancement, MayTheSourceBeWithYou
