Repository puppetlabs/pdk, pull requests merged in 2023-06, with the labels that each got.

#1253 (CONT-1030) Fix undefined method error
  package-testing/spec/spec_helper_package.rb
Labels: maintenance

#1252 (CONT-1027) Deprecate pe-version option
  .rubocop_todo.yml
  README.md
  docs/pdk_install.md
  docs/pdk_reference.md
  docs/pdk_testing.md
  lib/pdk/cli.rb
  lib/pdk/cli/util.rb
  lib/pdk/util/puppet_version.rb
  spec/acceptance/version_changer_spec.rb
  spec/unit/pdk/cli/console_spec.rb
  spec/unit/pdk/cli/test/unit_spec.rb
  spec/unit/pdk/cli/util_spec.rb
  spec/unit/pdk/cli/validate_spec.rb
  spec/unit/pdk/util/puppet_version_spec.rb
  spec/unit/pdk/validate/invokable_validator_spec.rb
Labels: enhancement

#1255 (CONT-1053) Update bundle command
  lib/pdk/cli/bundle.rb
Labels: enhancement

#1165 Take "operatingsystem_support" parameter from answer.json
  .rubocop_todo.yml
  lib/pdk/generate/module.rb
  lib/pdk/module/metadata.rb
Labels: enhancement

#1257 (MAINT) Fixup Puppet versions
  package-testing/spec/package/version_selection_spec.rb
Labels: maintenance

#1259 (CONT-1069) Update compatibility handling
  lib/pdk/cli/util.rb
  spec/unit/pdk/cli/util_spec.rb
Labels: bug

#1258 (CONT-990) - Community Pull Requests template
  .github/pull_request_template.md
Labels: maintenance

#1260 (CONT-1130) Bump PDK gem version
  lib/pdk/version.rb
Labels: backwards-incompatible

#1261 (CONT-990) - Adding Community Pull Requests template for tools
  .github/pull_request_template.md
Labels: maintenance

#1263 (CONT-1154) Disable console command
  README.md
  docs/pdk_overview.md
  lib/pdk/cli.rb
  spec/unit/pdk/cli/console_spec.rb
Labels: backwards-incompatible

#1264 (CONT-1134) Bump PDK Templates REF
  lib/pdk/version.rb
Labels: backwards-incompatible

#1265 (maint) Update minor typo
  lib/pdk/cli/util.rb
  spec/unit/pdk/cli/util_spec.rb
Labels: maintenance
