Repository puppetlabs/pdk, pull requests merged in 2023-01, with the labels that each got.

#1195 (CONT-422) PDK v2.6.0
  lib/pdk/version.rb
  package-testing/Gemfile
  package-testing/spec/package/version_selection_spec.rb
Labels: enhancement

#1196 (CONT-422) - PDK 2.6.0 Release Notes
  CHANGELOG.md
  docs/release_notes_pdk.md
Labels: maintenance

#1194 (CONT-437) Identify Packages Owned By Puppet
  README.md
  docs/pdk_overview.md
Labels: documentation

#1197 (CONT-422) - Update docs post 2.6.0 release
  docs/pdk.md
  docs/release_notes_pdk.md
Labels: maintenance

#1200 (MAINT) Release prep for v2.6.1
  CHANGELOG.md
  docs/pdk_known_issues.md
  docs/release_notes_pdk.md
  lib/pdk/version.rb
Labels: maintenance

#1203 (CONT-479) Bump nokogiri
  package-testing/Gemfile
Labels: maintenance

#1204 (CONT-479) Remove JSON and activesupport gems
  Gemfile
Labels: maintenance
