Repository puppetlabs/pdk, pull requests merged in 2023-02, with the labels that each got.

#1208 pdksync - (CONT-211) Adding mend config
  .github/workflows/mend.yml
Labels: maintenance

#1207 Add Puppet validator for plans
  lib/pdk/validate.rb
  lib/pdk/validate/puppet/puppet_plan_syntax_validator.rb
  lib/pdk/validate/puppet/puppet_validator_group.rb
  spec/unit/pdk/validate/puppet/puppet_plan_syntax_validator_spec.rb
Labels: enhancement

#1198 (CONT-487) CI updates
  .github/workflows/acceptance.yml
  .github/workflows/ci.yml
  .github/workflows/labeller.yml
  .github/workflows/release.yml
  .github/workflows/release_prep.yml
  .gitignore
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile
  appveyor.yml
  lib/pdk/util/changelog_generator.rb
  spec/acceptance/bundle_spec.rb
  spec/unit/pdk/config/namespace_spec.rb
  spec/unit/pdk/validate/puppet/puppet_plan_syntax_validator_spec.rb
  spec/unit/pdk/validate/ruby/ruby_rubocop_validator_spec.rb
Labels: maintenance

#1212 (CONT-650) Bump dependencies
  Gemfile
  Rakefile
  package-testing/Gemfile
  pdk.gemspec
Labels: maintenance

#1213 (CONT-644) Bump gem version
  lib/pdk/version.rb
Labels: maintenance

#1215 (CONT-669) Use bundle info command
  lib/pdk/util/changelog_generator.rb
Labels: bug
