Repository puppetlabs/pdk, pull requests merged in 2024-01, with the labels that each got.

#1289 Support executable templates
  lib/pdk/module/convert.rb
  lib/pdk/module/update_manager.rb
  lib/pdk/template/renderer/v1/legacy_template_dir.rb
  lib/pdk/template/renderer/v1/renderer.rb
  lib/pdk/util/filesystem.rb
  spec/unit/pdk/module/convert_spec.rb
  spec/unit/pdk/module/update_manager_spec.rb
  spec/unit/pdk/util/filesystem_spec.rb
Labels: enhancement, community

#1304 (maint) - rubocop fixes
  package-testing/spec/package/support/serverspec_monkeypatch.rb
  spec/unit/pdk/config/namespace_spec.rb
Labels: maintenance

#1303 (CAT-1618) - Add Code Coverage to CI
  .github/workflows/ci.yml
  spec/spec_helper.rb
Labels: maintenance

#1308 (CAT-1688) - Pin rubocop to `~> 1.50.0`
  .rubocop_todo.yml
  Gemfile
  lib/pdk/config/namespace.rb
  lib/pdk/module/metadata.rb
Labels: bugfix

#1309 pdksync - (CAT-1618) - Remove deprecated/obsolete codecov gem
  Gemfile
  spec/spec_helper.rb
Labels: maintenance
