Repository puppetlabs/pdk, pull requests merged in 2024-07, with the labels that each got.

#1352 Skip 'name' validation when in a controlrepo context
  lib/pdk/module/convert.rb
  lib/pdk/module/metadata.rb
Labels: enhancement

#1376 pdksync - (CAT-1954) Remove labeller
  .github/workflows/labeller.yml
Labels: maintenance

#1374 (CAT-1896) - Use puppet-modulebuilder for `PDK build`
  lib/pdk/cli/build.rb
  lib/pdk/cli/release.rb
  lib/pdk/module/build.rb
  lib/pdk/module/release.rb
  lib/pdk/util.rb
  pdk.gemspec
  spec/unit/pdk/cli/build_spec.rb
  spec/unit/pdk/module/build_spec.rb
  spec/unit/pdk/module/release_spec.rb
Labels: enhancement

#1378 (CAT-648) - Mark release*.rb files as non-executable
  lib/pdk/cli/release.rb
  spec/unit/pdk/cli/release_spec.rb
Labels: bugfix

#1379 (CAT-1786) Remove Fedora 36 from the and add Fedora 40 to the PDK README
  docs/pdk_install.md
Labels: enhancement, documentation

#1380 (CAT-1988) Update the Supported Operating systems to be accurate
  docs/pdk_install.md
Labels: maintenance, documentation

#1381 (CAT-1928) Update Supported OS on new module to match what is expected
  lib/pdk/module/metadata.rb
  spec/acceptance/new_module_spec.rb
  spec/unit/pdk/generate/module_spec.rb
Labels: enhancement
