Repository puppetlabs/pdk, pull requests merged in 2024-10, with the labels that each got.

#1390 Use reusable workflow restarter
  .github/actions/workflow-restarter-proxy/README.md
  .github/actions/workflow-restarter-proxy/action.yml
  .github/actions/workflow-restarter-proxy/image-1.png
  .github/actions/workflow-restarter-proxy/image-2.png
  .github/actions/workflow-restarter-proxy/image-3.png
  .github/actions/workflow-restarter-proxy/image-4.png
  .github/actions/workflow-restarter-proxy/image.png
  .github/actions/workflow-restarter-proxy/workflow-restarter-test.yml.sample
  .github/actions/workflow-restarter-proxy/workflow-restarter.yml.using_gh
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .github/workflows/workflow-restarter-test.yml
  .github/workflows/workflow-restarter.yml
Labels: maintenance, github_actions

#1404 (CAT-2093) Enable shellcheck in CI
  .github/workflows/ci.yml
Labels: maintenance

#1403 (CAT-643) Add forge gem upload functionality
  lib/pdk/module/release.rb
  pdk.gemspec
  spec/unit/pdk/module/release_spec.rb
Labels: feature

#1410 (CAT-2130) Pin json to prevent issues
  pdk.gemspec
Labels: bugfix

#1409 (CAT-2121) Update tests to account for `pdk validate` changes
  pdk.gemspec
  spec/acceptance/report_spec.rb
  spec/acceptance/validate_all_spec.rb
  spec/acceptance/validate_puppet_spec.rb
Labels: maintenance

#1408 (maint) Fix Gem::Platform.match() deprecation warning
  lib/pdk/util/puppet_version.rb
Labels: bugfix
